import * as z from "zod/mini";

const UserPreferences = z.object({
  dark: z.optional(z.boolean()),
  transp: z.optional(z.boolean()),
  bgImg: z.optional(z.url()),
  is3d: z.optional(z.boolean()),
  theme: z.optional(
    z.literal([
      "blue",
      "blue2",
      "blue3",
      "blue-marble",
      "canvas",
      "wood",
      "wood2",
      "wood3",
      "wood4",
      "maple",
      "maple2",
      "brown",
      "leather",
      "green",
      "marble",
      "green-plastic",
      "grey",
      "metal",
      "olive",
      "newspaper",
      "purple",
      "purple-diag",
      "pink",
      "ic",
    ]),
  ),
  pieceSet: z.optional(
    z.literal([
      "cburnett",
      "merida",
      "alpha",
      "pirouetti",
      "chessnut",
      "chess7",
      "reillycraig",
      "companion",
      "riohacha",
      "kosal",
      "leipzig",
      "fantasy",
      "spatial",
      "california",
      "pixel",
      "maestro",
      "fresca",
      "cardinal",
      "gioco",
      "tatiana",
      "staunty",
      "governor",
      "dubrovny",
      "icpieces",
      "shapes",
      "letter",
    ]),
  ),
  theme3d: z.optional(
    z.literal([
      "Black-White-Aluminium",
      "Brushed-Aluminium",
      "China-Blue",
      "China-Green",
      "China-Grey",
      "China-Scarlet",
      "Classic-Blue",
      "Gold-Silver",
      "Light-Wood",
      "Power-Coated",
      "Rosewood",
      "Marble",
      "Wax",
      "Jade",
      "Woodi",
    ]),
  ),
  pieceSet3d: z.optional(
    z.literal([
      "Basic",
      "Wood",
      "Metal",
      "RedVBlue",
      "ModernJade",
      "ModernWood",
      "Glass",
      "Trimmed",
      "Experimental",
      "Staunton",
      "CubesAndPi",
    ]),
  ),
  soundSet: z.optional(
    z.literal([
      "silent",
      "standard",
      "piano",
      "nes",
      "sfx",
      "futuristic",
      "robot",
      "music",
      "speech",
    ]),
  ),
  blindfold: z.optional(z.int()),
  autoQueen: z.optional(z.int()),
  autoThreefold: z.optional(z.int()),
  takeback: z.optional(z.int()),
  moretime: z.optional(z.int()),
  clockTenths: z.optional(z.int()),
  clockBar: z.optional(z.boolean()),
  clockSound: z.optional(z.boolean()),
  premove: z.optional(z.boolean()),
  animation: z.optional(z.int()),
  pieceNotation: z.optional(z.int()),
  captured: z.optional(z.boolean()),
  follow: z.optional(z.boolean()),
  highlight: z.optional(z.boolean()),
  destination: z.optional(z.boolean()),
  coords: z.optional(z.int()),
  replay: z.optional(z.int()),
  challenge: z.optional(z.int()),
  message: z.optional(z.int()),
  submitMove: z.optional(z.int()),
  confirmResign: z.optional(z.int()),
  insightShare: z.optional(z.int()),
  keyboardMove: z.optional(z.int()),
  voiceMove: z.optional(z.boolean()),
  zen: z.optional(z.int()),
  ratings: z.optional(z.int()),
  moveEvent: z.optional(z.int()),
  rookCastle: z.optional(z.int()),
  flairs: z.optional(z.boolean()),
  sayGG: z.optional(z.literal([0, 1, 2])),
});

type UserPreferences = z.infer<typeof UserPreferences>;

export { UserPreferences };
