import * as z from "zod";

const UserPreferences = z.object({
  dark: z.boolean().optional(),
  transp: z.boolean().optional(),
  bgImg: z.url().optional(),
  is3d: z.boolean().optional(),
  theme: z
    .literal([
      "blue",
      "blue2",
      "blue3",
      "blue-marble",
      "canvas",
      "wood",
      "wood2",
      "wood3",
      "wood4",
      "maple",
      "maple2",
      "brown",
      "leather",
      "green",
      "marble",
      "green-plastic",
      "grey",
      "metal",
      "olive",
      "newspaper",
      "purple",
      "purple-diag",
      "pink",
      "ic",
    ])
    .optional(),
  pieceSet: z
    .literal([
      "cburnett",
      "merida",
      "alpha",
      "pirouetti",
      "chessnut",
      "chess7",
      "reillycraig",
      "companion",
      "riohacha",
      "kosal",
      "leipzig",
      "fantasy",
      "spatial",
      "california",
      "pixel",
      "maestro",
      "fresca",
      "cardinal",
      "gioco",
      "tatiana",
      "staunty",
      "governor",
      "dubrovny",
      "icpieces",
      "shapes",
      "letter",
    ])
    .optional(),
  theme3d: z
    .literal([
      "Black-White-Aluminium",
      "Brushed-Aluminium",
      "China-Blue",
      "China-Green",
      "China-Grey",
      "China-Scarlet",
      "Classic-Blue",
      "Gold-Silver",
      "Light-Wood",
      "Power-Coated",
      "Rosewood",
      "Marble",
      "Wax",
      "Jade",
      "Woodi",
    ])
    .optional(),
  pieceSet3d: z
    .literal([
      "Basic",
      "Wood",
      "Metal",
      "RedVBlue",
      "ModernJade",
      "ModernWood",
      "Glass",
      "Trimmed",
      "Experimental",
      "Staunton",
      "CubesAndPi",
    ])
    .optional(),
  soundSet: z
    .literal([
      "silent",
      "standard",
      "piano",
      "nes",
      "sfx",
      "futuristic",
      "robot",
      "music",
      "speech",
    ])
    .optional(),
  blindfold: z.int().optional(),
  autoQueen: z.int().optional(),
  autoThreefold: z.int().optional(),
  takeback: z.int().optional(),
  moretime: z.int().optional(),
  clockTenths: z.int().optional(),
  clockBar: z.boolean().optional(),
  clockSound: z.boolean().optional(),
  premove: z.boolean().optional(),
  animation: z.int().optional(),
  pieceNotation: z.int().optional(),
  captured: z.boolean().optional(),
  follow: z.boolean().optional(),
  highlight: z.boolean().optional(),
  destination: z.boolean().optional(),
  coords: z.int().optional(),
  replay: z.int().optional(),
  challenge: z.int().optional(),
  message: z.int().optional(),
  submitMove: z.int().optional(),
  confirmResign: z.int().optional(),
  insightShare: z.int().optional(),
  keyboardMove: z.int().optional(),
  voiceMove: z.boolean().optional(),
  zen: z.int().optional(),
  ratings: z.int().optional(),
  moveEvent: z.int().optional(),
  rookCastle: z.int().optional(),
  flairs: z.boolean().optional(),
  sayGG: z.literal([0, 1, 2]).optional(),
});

type UserPreferences = z.infer<typeof UserPreferences>;

export { UserPreferences };
