name: Sync API docs

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  sync-api-docs:
    name: Sync API docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.CI_PAT }}

      - name: Checkout lichess-org/api
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: lichess-org/api
          ref: master
          path: lichess-api
          fetch-depth: 1

      - name: Copy files
        run: |
          rm -rf specs/*

          mkdir -p specs/schemas specs/tags

          cp -r lichess-api/doc/specs/schemas/.         specs/schemas/
          cp -r lichess-api/doc/specs/tags/.            specs/tags/
          cp    lichess-api/doc/specs/lichess-api.yaml  specs/lichess-api.yaml

          rm -rf lichess-api

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.CI_PAT }}
          commit-message: "chore: sync api docs"
          title: "chore: sync api docs"
          committer: CI <ci@rman.dev>
          author: CI <ci@rman.dev>
          branch: sync-api-docs
          delete-branch: true
          assignees: gameroman
          reviewers: gameroman
          labels: ci

      - name: Notify Discord
        if: always()
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Sync API docs (#${{ github.run_number }})"
          description: |
            Status: **${{ job.status }}**
            Branch: ${{ github.ref_name }}
            Trigger: ${{ github.event_name }}
            Commit: ${{ github.sha }}
